-- Create the reviews table
CREATE TABLE public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contract_id BIGINT REFERENCES public.contracts(id) ON DELETE CASCADE NOT NULL,
  instructor_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  company_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT one_review_per_contract UNIQUE (contract_id)
);

-- Enable Row Level Security
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- RLS Policies for reviews
-- Anyone can view reviews
CREATE POLICY "Reviews are public" ON public.reviews
  FOR SELECT USING (true);

-- Only the company involved in a paid contract can create a review
CREATE POLICY "Companies can create reviews for their paid contracts" ON public.reviews
  FOR INSERT WITH CHECK (
    auth.uid() = company_id AND
    EXISTS (
      SELECT 1 FROM public.contracts
      WHERE id = contract_id AND status = 'paid' AND company_id = auth.uid()
    )
  );
