-- Create the jobs table
create table jobs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  budget numeric,
  company_id uuid not null references public.profiles(id),
  status text default 'open' not null check (status in ('open', 'in_progress', 'closed'))
);

-- Set up Row Level Security
alter table jobs enable row level security;

create policy "Jobs are viewable by everyone." on jobs
  for select using (true);

create policy "Companies can insert their own jobs." on jobs
  for insert with check (auth.uid() = company_id and (select role from profiles where id = auth.uid()) = 'company');

create policy "Companies can update their own jobs." on jobs
  for update using (auth.uid() = company_id and (select role from profiles where id = auth.uid()) = 'company');

create policy "Companies can delete their own jobs." on jobs
  for delete using (auth.uid() = company_id and (select role from profiles where id = auth.uid()) = 'company');
